### ISSUE TITLE
NoSuchMethod error in 2.10 project when used with sbt-coursier

### ISSUE THREAD

**Issue by lloydmeta** [lucidsoftware/neo-sbt-scalafmt#14]
When I try to clean+compile a cross-compiled project that has both neo-sbt-scalafmt and sbt-coursier, when `scalaVersion` is 2.10, I get the following error when running `scalafmt`:

`java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
`

I'm unsure what the cause is, but it looks like one or both of the plugins might be using conflicting versions of Scala Predef?

Here is the full stack trace

```scala
> last compile:scalafmt 
[info] Formatting 9 Scala sources in metascraper:compile ...
java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
        at metaconfig.typesafeconfig.TypesafeConfig2Class$$anonfun$1.apply(TypesafeConfig2Class.scala:30)
        at metaconfig.typesafeconfig.TypesafeConfig2Class$$anonfun$1.apply(TypesafeConfig2Class.scala:30)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.mutable.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:45)
        at scala.collection.SetLike$class.map(SetLike.scala:93)
        at scala.collection.mutable.AbstractSet.map(Set.scala:45)
        at metaconfig.typesafeconfig.TypesafeConfig2Class$.metaconfig$typesafeconfig$TypesafeConfig2Class$$loop$1(TypesafeConfig2Class.scala:30)
        at metaconfig.typesafeconfig.TypesafeConfig2Class$.gimmeSafeConf(TypesafeConfig2Class.scala:48)
        at metaconfig.typesafeconfig.TypesafeConfig2Class$.gimmeConfFromString(TypesafeConfig2Class.scala:12)
        at metaconfig.typesafeconfig.package$$anon$1.fromInput(package.scala:13)
        at org.scalafmt.config.Config$.fromInput(Config.scala:45)
        at org.scalafmt.config.Config$.fromHoconString(Config.scala:55)
        at org.scalafmt.config.Config.fromHoconString(Config.scala)
        at com.lucidchart.scalafmt.impl.Scalafmtter.config(Scalafmtter.java:12)
        at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$9.config$lzycompute$1(ScalafmtCorePlugin.scala:85)
        at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$9.com$lucidchart$sbt$scalafmt$ScalafmtCorePlugin$autoImport$$anonfun$$config$1(ScalafmtCorePlugin.scala:85)
        at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$9$$anonfun$15$$anonfun$apply$7.apply(ScalafmtCorePlugin.scala:88)
        at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$9$$anonfun$15$$anonfun$apply$7.apply(ScalafmtCorePlugin.scala:87)
        at scala.util.Either$LeftProjection.flatMap(Either.scala:364)
        at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$9$$anonfun$15.apply(ScalafmtCorePlugin.scala:86)
        at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$9$$anonfun$15.apply(ScalafmtCorePlugin.scala:86)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$9.apply(ScalafmtCorePlugin.scala:86)
        at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$9.apply(ScalafmtCorePlugin.scala:44)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by pauldraper** [comment]
Unfortunately, coursier resolves dependencies differently than sbt.

See https://github.com/lucidsoftware/neo-sbt-scalafmt/issues/1 and and https://github.com/coursier/coursier/issues/543

**Comment by lloydmeta** [comment]
@pauldraper I see. Thanks, I'll close this bug since it's a dupe :)

**Comment by pauldraper** [comment]
1.3 adds sbt-scalafmt-coursier that will work.

**Comment by lloydmeta** [comment]
Wow! Thanks. Will check it out.
