### ISSUE TITLE
java.lang.NoSuchMethodError STRIKES AGAIN

### ISSUE THREAD

**Issue by fommil** [lucidsoftware/neo-sbt-scalafmt#26]
like #16 , but even with the proposed fix the following will cause an exception on startup

```
scalafmtOnCompile := true
```

the problem is that it tries to format the `sbt` files and obviously there is a problem there

```
[info] Compiling 1 Scala source to /home/fommil/Projects/foo/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to foo (in build file:/home/fommil/Projects/foo/)
[info] Formatting 1 Scala source in foo:sbt ...
java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
	at scala.meta.inputs.Input$String.<init>(Input.scala:23)
	at scala.meta.inputs.Input$String$.apply(Input.scala:23)
	at org.scalafmt.config.Config$.fromHoconString(Config.scala:55)
	at com.lucidchart.scalafmt.impl.ScalafmtFactory.fromConfig(ScalafmtFactory.scala:12)
```

is it possible to disable autoformat for the `project` and `.sbt` files for now?

**Comment by fommil** [comment]
dang. even normal formatting is failing for this project. I have no idea what it could be, I'm using

```
addSbtPlugin("com.lucidchart" % "sbt-scalafmt-coursier" % "1.7")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC5")
```

**Comment by fommil** [comment]
hmm, this is a dead giveaway. Look, the scala version is 2.11 and doesn't match what scalafmt requires. I don't think the `-coursier` workaround is working

```
[info] 	List(org.wartremover:wartremover:2.1.0:plugin->default(compile), org.scala-lang:scala-library:2.11.11, com.geirsson:scalafmt-core_2.12:1.0.0-RC4:scalafmt, com.lucidchart:scalafmt-impl_2.12:1.7-1.0:scalafmt, com.geirsson:scalafmt-core_2.12:1.0.0-RC4:scalafmt, com.lucidchart:scalafmt-impl_2.12:1.7-1.0:scalafmt, com.typesafe.scala-logging:scala-logging:3.5.0, com.typesafe.akka:akka-slf4j:2.4.18, ch.qos.logback:logback-classic:1.2.3, org.slf4j:log4j-over-slf4j:1.7.25, org.slf4j:slf4j-api:1.7.25, org.slf4j:jul-to-slf4j:1.7.25, org.slf4j:jcl-over-slf4j:1.7.25, com.typesafe:config:1.3.1, org.codehaus.janino:janino:2.7.8:test, org.scalatest:scalatest:3.0.3:test, org.scalacheck:scalacheck:1.13.5:test, com.typesafe.scala-logging:scala-logging:3.5.0:test, com.typesafe.akka:akka-slf4j:2.4.18:test, ch.qos.logback:logback-classic:1.2.3:test, org.slf4j:log4j-over-slf4j:1.7.25:test, org.slf4j:slf4j-api:1.7.25:test, org.slf4j:jul-to-slf4j:1.7.25:test, org.slf4j:jcl-over-slf4j:1.7.25:test, org.spire-math:kind-projector:0.9.3:plugin->default(compile))
```

**Comment by pauldraper** [comment]
Not a fix, but FYI, disable sbt autocompilation with either

(1) A .scalafmt.conf project.exclude filter.
(2) sbt `scalafmtOnCompile in Sbt := false`

**Comment by pauldraper** [comment]
I can't reproduce with a simple example.

```project/plugins.sbt
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC5")
addSbtPlugin("com.lucidchart" % "sbt-scalafmt-coursier" % "1.7")
```

```build.sbt
scalafmtOnCompile :=  true
```

```
$ sbt -batch -sbt-version 0.13.15 exit
[info] Loading global plugins from /home/paul/.sbt/0.13/plugins
[info] Loading project definition from /home/paul/test21/project
[info] Set current project to test21 (in build file:/home/paul/test21/)
[info] Formatting 1 Scala source in test21:sbt ...
[info] Reformatted 1 Scala source in test21:sbt
[success] Total time: 1 s, completed Jun 28, 2017 10:42:16 PM
```

**Comment by pauldraper** [comment]
Hm, I do get an error with sbt 1.0.0-M6, but it's ` (sbt:scalafmt::scalafmt) java.lang.NoSuchMethodError: com.lucidchart.scalafmt.api.Scalafmtter.formatter(Lcom/lucidchart/scalafmt/api/Dialect;)Ljava/util/function/Function;
`

That's different though. (EDIT: due to https://github.com/sbt/sbt/issues/3244, will be fixed when sbt project updates its version of sbt-scalafmt)

What is the output of `inspect scalafmt::externalDependencyClasspath`?

That should tell us if the sbt-scalafmt-coursier stuff is doing its thing.

**Comment by fommil** [comment]
Not at my computer right now but I posted a follow up comment.

I might be able to create a reproduction, but it won't be minimal, because we have quite a lot of defaults/plugins. But at least it's somewhere to start.

**Comment by fommil** [comment]
well it's not minimal, but this reproduces it

https://github.com/fommil/neo-sbt-scalafmt/tree/coursier-bug

I will start stripping things out of https://github.com/cakesolutions/sbt-cake/tree/v1.0.3 until the problem is minimised.

**Comment by fommil** [comment]
ok, I minimised it in https://github.com/fommil/neo-sbt-scalafmt/tree/coursier-bug

Looks like a combination of hacking on autoload for this plugin plus setting a custom `dependencyOverrides` for `scala-lang`.

**Comment by fommil** [comment]
@alexarchambault you may be interested... (sorry, I keep breaking things)

**Comment by fommil** [comment]
could this be because it is now auto-loaded?

**Comment by fommil** [comment]
closing as a crazy corner case

**Comment by pauldraper** [comment]
That case works for me

```
$ sbt scalafmt
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading global plugins from /home/paul/.sbt/0.13/plugins
[info] Loading project definition from /home/paul/dev/neo-sbt-scalafmt/project
[info] Updating {file:/home/paul/dev/neo-sbt-scalafmt/project/}neo-sbt-scalafmt-build...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 2 Scala sources to /home/paul/dev/neo-sbt-scalafmt/project/target/scala-2.10/sbt-0.13/classes...
[warn] Class javax.annotation.Nullable not found - continuing with a stub.
[warn] Class javax.annotation.Nullable not found - continuing with a stub.
[warn] Class javax.annotation.Nullable not found - continuing with a stub.
[warn] Class javax.annotation.Nullable not found - continuing with a stub.
[warn] Class javax.annotation.Nullable not found - continuing with a stub.
[warn] Class javax.annotation.CheckReturnValue not found - continuing with a stub.
[warn] 6 warnings found
[info] Set current project to neo-sbt-scalafmt (in build file:/home/paul/dev/neo-sbt-scalafmt/)
[info] Fetching scalafmt for {file:/home/paul/dev/neo-sbt-scalafmt/}neo-sbt-scalafmt
[info] Fetched 26 artifacts for scalafmt
[info] Formatting 2 Scala sources in neo-sbt-scalafmt:compile ...
[success] Total time: 2 s, completed Jun 30, 2017 9:23:13 AM
```
I'm also happy to look at a less minimal case if you'd like.

In any case, hacking the autoload shouldn't be needed anymore.
