### ISSUE TITLE
Fails with scalafmt 1.1.0

### ISSUE THREAD

**Issue by nrinaudo** [lucidsoftware/neo-sbt-scalafmt#29]
When setting the scalafmt to 1.1.0, I'm getting the following error message:
```
warning: Unknown Scalafmt version 1.1.0; using 1.0 interface
scala.MatchError: 1.0 (of class java.lang.String)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$$anonfun$37.apply(ScalafmtCorePlugin.scala:243)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$$anonfun$37.apply(ScalafmtCorePlugin.scala:242)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] scala.MatchError: 1.0 (of class java.lang.String)
```

I would assume it has something to do with [this](https://github.com/lucidsoftware/neo-sbt-scalafmt/blob/master/sbt-scalafmt/src/main/scala/com/lucidchart/sbt/scalafmt/ScalafmtCorePlugin.scala#L245) bit of code, but I might be missing something.

**Comment by olafurpg** [comment]
FWIW, the 1.x series will be binary compatible with each other

**Comment by hseeberger** [comment]
It's this line: https://github.com/lucidsoftware/neo-sbt-scalafmt/blob/master/sbt-scalafmt/src/main/scala/com/lucidchart/sbt/scalafmt/ScalafmtCorePlugin.scala#L248

We need to return a tuple. Will send a PR.

**Comment by fommil** [comment]
should it still log out when 1.1.0 is used though?
