### ISSUE TITLE
scalafmtOnCompile 1.8 error in meta-builds

### ISSUE THREAD

**Issue by kshakir** [lucidsoftware/neo-sbt-scalafmt#31]
Hi,

I'm wondering if you could help with an error I'm seeing with version neo-sbt-scalafmt 1.8 with scalafmt 1.x.

I have a project that has been successfully formatting not only the source, but also the [meta-build](https://github.com/lucidsoftware/neo-sbt-scalafmt/tree/1.8#formatting-build-files) (build.sbt, project/*).

This example below works fine with `ScalafmtVersion=1.0.0` + `SbtScalafmtVersion=1.7`, and even formats the `build.sbt` whenever a basic `sbt` is run.

Due to #29, in order to use `ScalafmtVersion=1.1.0`, I also needed to bump the `SbtScalafmtVersion=1.8`. FYI, the error below occurs whether or not I switch from `ScalafmtVersion=1.1.0` to `ScalafmtVersion=1.0.0`.

Thanks!

---

**build.sbt**
```scala
val ScalafmtVersion = "1.1.0"
//val ScalafmtVersion = "1.0.0"

scalafmtVersion in ThisBuild := ScalafmtVersion
scalafmtOnCompile in ThisBuild := true
ignoreErrors in (ThisBuild, scalafmt) := false
```

**project/build.properties**
```scala
sbt.version=0.13.15
```

**project/plugins.sbt**
```scala
val SbtScalafmtVersion = "1.8"
val ScalafmtVersion = "1.1.0"
//val SbtScalafmtVersion = "1.7"
//val ScalafmtVersion = "1.0.0"

addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % SbtScalafmtVersion)

scalafmtVersion in ThisBuild := ScalafmtVersion
scalafmtOnCompile in ThisBuild := true
ignoreErrors in (ThisBuild, scalafmt) := false
```

**project/project/plugins.sbt**
```scala
val SbtScalafmtVersion = "1.8"

addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % SbtScalafmtVersion)
```

`sbt` **output**

```scala
neo-sbt-scalafmt-error$ sbt
[info] Loading global plugins from /Users/kshakir/.sbt/0.13/plugins
[info] Loading project definition from /Users/kshakir/src/neo-sbt-scalafmt-error/project/project
Warning: Unknown Scalafmt version 1.1.0; using 1.0 interface
[info] Loading project definition from /Users/kshakir/src/neo-sbt-scalafmt-error/project
[info] Formatting 1 Scala source in {file:/Users/kshakir/src/neo-sbt-scalafmt-error/project/}/neo-sbt-scalafmt-error-build:compile ...
<input>:1: error: expected class or object definition
val SbtScalafmtVersion = "1.8"
^
	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:17)
	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:17)
	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:18)
	at scala.meta.internal.parsers.Reporter.syntaxError$(Reporter.scala:18)
	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
	at scala.meta.internal.parsers.ScalametaParser.statSeq(ScalametaParser.scala:3527)
	at scala.meta.internal.parsers.ScalametaParser.topStatSeq(ScalametaParser.scala:3542)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$batchSource$1(ScalametaParser.scala:3778)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:401)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:407)
	at scala.meta.internal.parsers.ScalametaParser.batchSource(ScalametaParser.scala:3748)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$source$1(ScalametaParser.scala:3733)
	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:401)
	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:407)
	at scala.meta.internal.parsers.ScalametaParser.source(ScalametaParser.scala:3732)
	at scala.meta.internal.parsers.ScalametaParser.$anonfun$parseSource$1(ScalametaParser.scala:153)
	at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:42)
	at scala.meta.internal.parsers.ScalametaParser.parseSource(ScalametaParser.scala:153)
	at scala.meta.parsers.Parse$.$anonfun$parseSource$1(Parse.scala:31)
	at scala.meta.internal.parsers.ScalametaParser$$anon$202.apply(ScalametaParser.scala:3788)
	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:21)
	at org.scalafmt.Scalafmt$.format(Scalafmt.scala:47)
	at com.lucidchart.scalafmt.impl.Scalafmtter$$anon$1.apply(Scalafmtter.scala:19)
	at com.lucidchart.scalafmt.impl.Scalafmtter$$anon$1.apply(Scalafmtter.scala:14)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$7$$anonfun$apply$1.apply(ScalafmtCorePlugin.scala:55)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$7$$anonfun$apply$1.apply(ScalafmtCorePlugin.scala:53)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$11$$anonfun$17$$anonfun$apply$8.apply(ScalafmtCorePlugin.scala:119)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$11$$anonfun$17$$anonfun$apply$8.apply(ScalafmtCorePlugin.scala:117)
	at scala.util.Either$LeftProjection.flatMap(Either.scala:364)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$11$$anonfun$17.apply(ScalafmtCorePlugin.scala:117)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$11$$anonfun$17.apply(ScalafmtCorePlugin.scala:117)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$11.apply(ScalafmtCorePlugin.scala:117)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$11.apply(ScalafmtCorePlugin.scala:77)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (compile:scalafmt::scalafmt) <input>:1: error: expected class or object definition
[error] val SbtScalafmtVersion = "1.8"
[error] ^
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
neo-sbt-scalafmt-error$ 
```

**Comment by danxmoran** [comment]
Reverting 3e9b1a7e4b88bb24e0e01b053550c643734ed0e3 makes the error go away. From a quick digging, I think the [default include filter](https://github.com/scalameta/scalafmt/blob/master/scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala#L10) will accept both Scala and SBT files, so filtering for sources from `baseDirectory` instead of `sourceDirectories` results in the build files also being included in `sources` within `ScalafmtPlugin`. However, the settings used in `ScalafmtPlugin` expect [only Scala files](https://github.com/lucidsoftware/neo-sbt-scalafmt/blob/master/sbt-scalafmt/src/main/scala/com/lucidchart/sbt/scalafmt/ScalafmtCorePlugin.scala#L198), so when it tries to format the SBT files it blows up.

**Comment by kmudrick** [comment]
Yeah this bug is kind of annoying.  If I use 1.7 of the plugin, I can't use 1.1.0 of scalafmt. But if I use 1.8 of the plugin, it tries to feed `.sbt` files to the formatter and it craps out.
