### ISSUE TITLE
coursier repositories seems to be ignore?

### ISSUE THREAD

**Issue by fommil** [lucidsoftware/neo-sbt-scalafmt#61]
I'm using this to try and use a snapshot

```
      scalafmtVersion := "1.3.0+14-910a2ed5",
      scalafmtCoursierRepositories += coursier.MavenRepository("https://dl.bintray.com/scalameta/maven/")
```

but I get

```
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/scalafmt/config/Config$
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2205)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$$anonfun$30$$anon$1$$anonfun$load$1.apply(ScalafmtCorePlugin.scala:239)
```

on sbt startup

**Comment by fommil** [comment]
this seems to be coming from the `sbt:scalafmt` task
